site_name: SeAT Documentation
site_description: SeAT Documentation
repo_url: https://github.com/eveseat/docs
pages:
    - Home: index.md
    - General:
        - Contact: general/contact.md
        - Reporting Bugs : general/reporting_bugs.md
        - Community Packages: general/community_packages.md
        - TODO List: general/todo.md
    - Guides:
      - Installation Guides:
          - Getting Started: guides/installation/getting_started.md
          - Quick Install: guides/installation/quick_install.md
          - Docker: guides/installation/docker.md
          - CentOS 6.x: guides/installation/centos6.md
          - CentOS 7.x: guides/installation/centos7.md
          - Ubuntu: guides/installation/ubuntu.md
          - Debian: guides/installation/debian.md
          - Developer Installation: guides/installation/developer_installation.md
      - Upgrade Guides:
          - General Upgrades: guides/upgrade/general_upgrades.md
          - SeAT 1.0 to SeAT 2.0: guides/upgrade/seat1_to_2.md
          - SeAT 2.0 to SeAT 3.0: guides/upgrade/seat2_to_3.md
      - Admin Guides:
          - Email Setup:
              - Using Mailgun: guides/admin/email/mailgun.md
              - Using Gmail: guides/admin/email/gmail.md
          - Configuring Eve Online SSO: guides/admin/sso.md
          - Job Queue Flow: guides/admin/job_queue_flow.md
          - Scaled SeAT Deployments: guides/admin/scaling_seat.md
          - Role Based Access Control: guides/admin/rbac.md
          - Understanding Tracking: guides/admin/tracking.md
          - EVE Api Administrative Contact: guides/admin/eveapi_admin_contact.md
          - Package Configurations:
              - Overview: guides/configuration/overview.md
              - Api: guides/configuration/api.md
              - Console: guides/configuration/console.md
              - Eveapi: guides/configuration/eveapi.md
              - Notifications: guides/configuration/notifications.md
              - Service: guides/configuration/service.md
              - Web: guides/configuration/web.md
              - Other: guides/configuration/other.md
      - Developers Guides:
          - General Guide: guides/development/general.md
          - Core Package Breakdown: guides/development/package_breakdown.md
          - Package Development: guides/development/package_development.md
    - SeAT API: seat_api.md
    - Changelogs:
        - Api: changelogs/api.md
        - Console: changelogs/console.md
        - Eveapi: changelogs/eveapi.md
        - Notifications: changelogs/notifications.md
        - Services: changelogs/services.md
        - Web: changelogs/web.md
theme: mkdocs
dev_addr: 0.0.0.0:9010
extra_css: [css/extra.css]
markdown_extensions:
    - admonition
    - toc:
        permalink: 