# Information
site_name: 'SeAT Documentation'
site_description: 'Simple EVE Api Tool Documentation'
site_url: 'https://github.com/eveseat/docs'

# Repository
repo_name: 'eveseat/docs'
repo_url: 'https://github.com/eveseat/docs'

# Copyright
copyright: 'Copyright &copy; 2015 - 2018 Leon Jacobs'

# Documentation TOC
pages:
    - Home: index.md
    - Requirements: general/requirements.md
    - Basic Installation: guides/installation/basic_installation/installation.md
    - Advanced Installation:
        - Getting Started: guides/installation/manual_installation/getting_started.md
        - CentOS: guides/installation/manual_installation/centos.md
        - Debian: guides/installation/manual_installation/debian.md
        - Docker: guides/installation/manual_installation/docker.md
        - Manual: guides/installation/manual_installation/manual.md
        - Ubuntu: guides/installation/manual_installation/ubuntu.md
    - Admin Guides:
        - Docker Admin:  guides/admin/docker.md
        - Configuring ESI: guides/installation/basic_installation/esi.md
        - Email Setup:
            - Using Mailgun: guides/admin/email/mailgun.md
            - Using Gmail: guides/admin/email/gmail.md
        - Env File Reference: guides/admin/env_reference.md
        - Job Queue Flow: guides/admin/job_queue_flow.md
        - Scaled SeAT Deployments: guides/admin/scaling_seat.md
        - Role Based Access Control: guides/admin/rbac.md
        - Understanding Tracking: guides/admin/tracking.md
        - EVE Api Administrative Contact: guides/admin/eveapi_admin_contact.md
        - Package Configurations:
            - Overview: guides/configuration/overview.md
            - Api: guides/configuration/api.md
            - Console: guides/configuration/console.md
            - Eveapi: guides/configuration/eveapi.md
            - Notifications: guides/configuration/notifications.md
            - Service: guides/configuration/service.md
            - Web: guides/configuration/web.md
            - Other: guides/configuration/other.md
        - Upgrade Guides:
            - General Upgrades: guides/admin/upgrade/general_upgrades.md
            - SeAT 1.0 to SeAT 2.0: guides/admin/upgrade/seat1_to_2.md
            - SeAT 2.0 to SeAT 3.0: guides/admin/upgrade/seat2_to_3.md
    - Webservers:
        - General: guides/installation/basic_installation/webserver.md
        - Traefik: guides/installation/basic_installation/traefik.md
        - Nginx: guides/installation/basic_installation/nginx.md
        - Apache: guides/installation/basic_installation/apache.md
    - Developers Guides:
        - Developer Installation: guides/development/developer_installation.md
        - General Guide: guides/development/general.md
        - Core Package Breakdown: guides/development/package_breakdown.md
        - Package Development: guides/development/package_development.md
        - SeAT API: guides/development/seat_api.md
    - Changelogs:
        - Api: changelogs/api.md
        - Console: changelogs/console.md
        - Eveapi: changelogs/eveapi.md
        - Notifications: changelogs/notifications.md
        - Services: changelogs/services.md
        - Web: changelogs/web.md
    - Community Packages: general/community_packages.md
    - About:
        - Contact: about/contact.md
        - Reporting Bugs : about/reporting_bugs.md
        - TODO List: about/todo.md

# Theme Configuration
theme:
    name: 'material'
    palette:
        primary: 'grey'
        accent: 'indigo'

google_analytics:
  - 'UA-119530306-1'
  - 'auto'

# Customization
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
extra:
  social:
    - type: 'github'
      link: 'https://github.com/eveseat/seat'
# Tabs customisation
extra_css:
    - css/extra_typo.css
    - css/extra_tabs.css
extra_javascript:
    - js/extra_tabs.js
