site_name: SeAT Documentation
site_description: SeAT Documentation
repo_url: https://github.com/eveseat/docs
pages:
    - Home: index.md
    - General:
        - Contact: contact.md
        - Reporting Bugs : reporting_bugs.md
        - Community Packages: community_packages.md
    - Setup Guides:
        - Quick Install: setup_guides/quick_install.md
        - CentOS 6.x: setup_guides/centos6.md
        - CentOS 7.x: setup_guides/centos7.md
        - Ubuntu 14.04.x: setup_guides/ubuntu1404.md
        - Upgrading SeAT: setup_guides/upgrade.md
    - Email:
        - Mailgun Setup: email/mailgun.md
    - Admin Guides:
        - Configuring Eve Online SSO: admin_guides/sso.md
        - Role Based Access Control: admin_guides/rbac.md
        - Understanding Tracking: admin_guides/tracking.md
    - SeAT API:
        - Overview: seat_api/overview.md
        - EVE Api Keys: seat_api/eve_api_keys.md
        - SeAT Users: seat_api/seat_users.md
        - SeAT Roles, Permissions and Authorization: seat_api/roles_permissions.md
        - Characters: seat_api/characters.md
        - Corporations: seat_api/corporations.md
    - Changelogs:
        - Api: changelogs/api.md
        - Console: changelogs/console.md
        - Eveapi: changelogs/eveapi.md
        - Notifications: changelogs/notifications.md
        - Services: changelogs/services.md
        - Web: changelogs/web.md
    - Package Configurations:
        - Overview: configuration/overview.md
        - Api: configuration/api.md
        - Console: configuration/console.md
        - Eveapi: configuration/eveapi.md
        - Notifications: configuration/notifications.md
        - Service: configuration/service.md
        - Web: configuration/web.md
        - Other: configuration/other.md
    - Eve XML API Updater:
        - Job Queue Flow: eve_xml_api_updater/job_queue_flow.md
    - Developing For SeAT:
        - General Guide: development/general.md
        - Core Package Breakdown: development/package_breakdown.md
        - Package Development: development/package_development.md
    - TODO List: todo.md
theme: readthedocs
